### ISSUE TITLE
OpenSSL certificate verify failed

### ISSUE THREAD

**Issue by nathany** [robowhois/robowhois-ruby#2]
I have some fairly simple code that was working but is failing now:

``` ruby
@robo = RoboWhois.new(api_key: ENV['ROBO_WHOIS_API_KEY'])
puts "Remaining RoboWhois credits: #{@robo.account['credits_remaining']}"
```

It gives this error:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

Ruby 2.1.3 (OS X 10.10). Yes, ROBO_WHOIS_API_KEY is set.

Any ideas?

**Comment by weppos** [comment]
@nathany we updated our server to remove SSLv3 negotiation. Can you retry and tell us if the issue is still happening?

**Comment by nathany** [comment]
That makes sense. I have no idea how to disable SSLv3 in Ruby, but I'll look into it.

**Comment by weppos** [comment]
@nathany It should not attempt to use SSLv3 anymore. Are you still experiencing the same issue?

**Comment by nathany** [comment]
Yes, still getting the SSLv3 error. I've updated to Ruby 2.1.4 as well.

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/nathany/.rvm/gems/ruby-2.1.4/gems/httparty-0.13.2/lib/httparty/request.rb:98:in `perform'
/Users/nathany/.rvm/gems/ruby-2.1.4/gems/httparty-0.13.2/lib/httparty.rb:539:in `perform_request'
/Users/nathany/.rvm/gems/ruby-2.1.4/gems/httparty-0.13.2/lib/httparty.rb:475:in `get'
/Users/nathany/.rvm/gems/ruby-2.1.4/gems/robowhois-0.5.0/lib/robo_whois.rb:97:in `request'
/Users/nathany/.rvm/gems/ruby-2.1.4/gems/robowhois-0.5.0/lib/robo_whois.rb:93:in `get'
/Users/nathany/.rvm/gems/ruby-2.1.4/gems/robowhois-0.5.0/lib/robo_whois.rb:65:in `account'
/Users/nathany/Development/landing/tasks/lib/domains/whois.rb:7:in `whois'
/Users/nathany/Development/landing/tasks/Rakefile:27:in `block (2 levels) in <top (required)>'
```
